// Hand-placed pixel art. Each sprite is a list of equal-width rows; each character is a PALETTE
// key and '.' is transparent. Heroes are 16×16 (OmniMan is taller), icons are 8×8.

export const SPRITES = Object.freeze({
  // The commander: navy-and-white suit, the Vertuoza stripes on the chest, grey streak, mustache.
  omni: [
    '......kkkkk.....',
    '.....khhhhgk....',
    '....khhhhhhgk...',
    '....khsssssgk...',
    '....ksesssesk...',
    '....ksssSsssk...',
    '....kshhhhhsk...',
    '.....ksssssk....',
    '......kSSSk.....',
    '...kkknwwwnkkk..',
    '..knnnwwwwwnnnk.',
    '.knnwwrrrwwwnnk.',
    '.knnwwwpppwwnnk.',
    '.knnwwoowwwwnnk.',
    '.kNnkwwwwwwknNk.',
    '.kNnkwwwwwwknNk.',
    '.knnkNNNNNNknnk.',
    '..kk.kwwkwwk.kk.',
    '.....kwwkwwk....',
    '.....kwwkwwk....',
    '.....knnknnk....',
    '.....knnknnk....',
    '....kknnkknnkk..',
    '....kkkk..kkkk..',
  ],
  // beaver fleet: goggles, buck teeth, flat tail.
  beaver: [
    '..kk........kk..',
    '.kbbkkkkkkkkbbk.',
    '.kbbbbbbbbbbbbk.',
    '.kcGGkbbbbkGGck.',
    '.kcGekbbbbkeGck.',
    '.kbkkbbbbbbkkbk.',
    '.kbbbttxxttbbbk.',
    '.kbbttttttttbbk.',
    '..kbbtqqqqtbbk..',
    '...kkbqkqkbkk...',
    '..knnkwwwwknnk..',
    '.knnwwrrwwwwnnk.',
    '.kbnwwppwwwwnbk.',
    '..knnwwwwwwnnkBk',
    '...kbbk..kbbkBBk',
    '...kkkk..kkkkkk.',
  ],
  // octopod fleet: violet head, pink tentacles, a suit collar.
  octopod: [
    '.....kkkkkk.....',
    '....kvvvvvvk....',
    '...kvvmvvvvvk...',
    '..kvvvvvvvvmvk..',
    '..kvvqkvvqkvvk..',
    '..kvvkkvvkkvvk..',
    '..kVvvvvvvvvVk..',
    '...kwnwwwwnwk...',
    '..kVvkwwppwkvVk.',
    '.kvVvkwwwwkvVvk.',
    '.kvkvVkkkkVvkvk.',
    'kvmkvmvkkvmvkmvk',
    'kmk.kvmk.kmvk.km',
    '.k..kmk...kmk..k',
    '....kk.....kk...',
    '................',
  ],
  // picsou fleet: a duck in goggles, a dollar on the chest, a coin in hand.
  picsou: [
    '.....kkkkk......',
    '....kqqqqqk.....',
    '...kqqqqqqqk....',
    '...kGGkqGGkqk...',
    '...kGekqeGkqk...',
    '...kqqqqqqoook..',
    '...kqqqqqoooook.',
    '....kqqqqkkkkk..',
    '...knnwwwwnnk...',
    '..knnwwyywwnnk..',
    '..kqnwyywwwnqky.',
    '..kqnwwyywwnqyYy',
    '...knnwwwwnnkyy.',
    '....knnkknnk....',
    '...kooookoooook.',
    '...kkkkk.kkkkk..',
  ],
  // cia fleet: the agency man. Sunglasses, dark suit, red tie.
  cia: [
    '.....kkkkkk.....',
    '....kssssssk....',
    '...kssssssssk...',
    '...kxxxkkxxxk...',
    '...kxcxkkxcxk...',
    '...ksssSSsssk...',
    '...ksskkkkssk...',
    '....kssssssk....',
    '...kkaawwaakk...',
    '..kaaaawrwaaaak.',
    '..kaaaawrwaaaak.',
    '..kaakawrwakaak.',
    '..kssk.aaa.kssk.',
    '....kaakaak.....',
    '....kxxkxxk.....',
    '....kkkkkkk.....',
  ],
  // invincible-team fleet: yellow suit, navy cowl, white lenses.
  invincible: [
    '.....kkkkkk.....',
    '....khhhhhhk....',
    '...knnnnnnnnk...',
    '...knqqnnqqnk...',
    '...knqqnnqqnk...',
    '...knnnnnnnnk...',
    '...kssssssssk...',
    '....kssSSssk....',
    '..kknnyyyynnkk..',
    '.knnnyyyyyynnnk.',
    '.knnkyynnyyknnk.',
    '.knnkyyyyyyknnk.',
    '.knnkyyyyyyknnk.',
    '..kk.kyykyyk.kk.',
    '.....knnknnk....',
    '....kkkk.kkkk...',
  ],
  // Entropy: the enemy. Every open wound is one of these on a planet. Recoloured per wound kind.
  entropy: [
    '....k..k....',
    '..kkPkkPkk..',
    '.kPPPPPPPPk.',
    'kPPpPPPPpPPk',
    'kPxrPPPPrxPk',
    'kPPPPPPPPPPk',
    'kPPkqkqkqPPk',
    'kPPPkkkkPPPk',
    '.kPPPPPPPPk.',
    'kPkPPkkPPkPk',
    'k.k.kk.kk.k.',
    '............',
  ],
  // Zone and planet icons, 8×8.
  flag: [
    'k.......',
    'kzzzz...',
    'kzZzzz..',
    'kzzzz...',
    'k.......',
    'k.......',
    'k.......',
    'kk......',
  ],
  hammer: [
    '.kkkk...',
    'kllllk..',
    'kAllAk..',
    '.kkbk...',
    '...kbk..',
    '....kbk.',
    '.....kbk',
    '......k.',
  ],
  fire: [
    '...r....',
    '..rr.r..',
    '.rror.r.',
    '.roorr..',
    'rooyor.r',
    'royyyor.',
    '.ryyyr..',
    '..rrr...',
  ],
  lock: [
    '..kkkk..',
    '.kl..lk.',
    '.kl..lk.',
    'kyyyyyyk',
    'kyYkkYyk',
    'kyYkkYyk',
    'kyyyyyyk',
    '.kkkkkk.',
  ],
  skull: [
    '.kkkkkk.',
    'kllllllk',
    'klxllxlk',
    'klxllxlk',
    'kllkkllk',
    '.kllllk.',
    '.klklkk.',
    '..kkkk..',
  ],
  beacon: [
    '.r....r.',
    'r.r..r.r',
    '.r.kk.r.',
    '...kk...',
    '..krrk..',
    '..kRRk..',
    '.kkRRkk.',
    'kkkkkkkk',
  ],
  coin: [
    '..kkkk..',
    '.kyyyyk.',
    'kyyYYyyk',
    'kyYyyyyk',
    'kyyYYyyk',
    'kyyyyYyk',
    '.kyYYyk.',
    '..kkkk..',
  ],
  check: [
    '........',
    '.......z',
    '......zZ',
    'z....zZ.',
    'Zz..zZ..',
    '.ZzzZ...',
    '..ZZ....',
    '........',
  ],
  open: [
    'yy....yy',
    'y......y',
    '........',
    '...yy...',
    '...yy...',
    '........',
    'y......y',
    'yy....yy',
  ],
  star: [
    '..q..',
    '..c..',
    'qcqcq',
    '..c..',
    '..q..',
  ],
  ship: [
    '...kk...',
    '..kwwk..',
    '..kwnk..',
    '.kwwwwk.',
    'kpwnnwpk',
    'kkwwwwkk',
    '..kppk..',
    '...cc...',
  ],
  cursor: [
    'yyy.',
    'y...',
    'y...',
    '....',
  ],
});

// Heroes by fleet (team names match the GitHub teams in projects.yml).
export const FLEET_SPRITE = Object.freeze({
  beaver: 'beaver', octopod: 'octopod', picsou: 'picsou', cia: 'cia', 'invincible-team': 'invincible',
});

// Entropy recoloured per wound kind (spec §5.3): the shape is the enemy, the colour says which one.
export const WOUND_TINT = Object.freeze({
  transmission: { P: '#2a7fa8', p: '#6ff0ff' },
  'unconfirmed-ground': { P: '#b85a12', p: '#ffb347' },
  beacon: { P: '#a8183a', p: '#ff3b5c' },
  'fault-line': { P: '#8a6a00', p: '#ffd84a' },
  'under-fire': { P: '#c2410c', p: '#ff9b30' },
  aftershock: { P: '#6d0f2a', p: '#ff3b5c' },
});
