// The linter (PRD 976): typescript-eslint's strictTypeChecked over every TypeScript file git tracks,
// tests linted the same as source, with two tunings — numbers print correctly in a template string,
// and React's hooks rules run on the arcade. An `eslint-disable` comment changes nothing
// (`noInlineConfig`), and scripts/typescript-guard.test.ts refuses one. `pnpm lint` runs it
// (scripts/lint.ts), which loads this file through Node's own type stripping.
import { defineConfig } from 'eslint/config';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

export default defineConfig(
  // Generated by `supabase gen types`, and the built bundle: no person writes either.
  { ignores: ['supabase/database.types.ts', 'kit/dist/'] },
  { linterOptions: { noInlineConfig: true } },
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    extends: [tseslint.configs.strictTypeChecked],
    languageOptions: {
      // Each file is read by the tsconfig nearest to it: the root's, or the arcade's.
      // packages/galaxy's index.d.ts stands beside the index.ts it declares, so no tsconfig's `include`
      // holds it (TypeScript keeps the .ts): it is read with the root tsconfig's options instead.
      parserOptions: {
        projectService: { allowDefaultProject: ['packages/galaxy/src/index.d.ts'], defaultProject: 'tsconfig.json' },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
    },
  },
  {
    files: ['apps/galaxy/**/*.{ts,tsx}'],
    // The plugin's own rules only: its `configs` do not meet ESLint's `Plugin` type.
    plugins: { 'react-hooks': { meta: reactHooks.meta, rules: reactHooks.rules } },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
    },
  },
);
