// pnpm galaxy:seed — regenerate supabase/seed.sql from the demo world, dated now.
// `supabase db reset` loads it, so a local stack opens on the same galaxy the demo mode shows.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { demoEvents, DEMO_PROJECTS } from '@omni/galaxy';
import { arr, json, lit } from './sql.mjs';

const out = fileURLToPath(new URL('../../../supabase/seed.sql', import.meta.url));
const now = new Date();
const events = demoEvents(now);

const lines = [
  `-- Generated by \`pnpm galaxy:seed\` on ${now.toISOString()}. Demo data: every PRD, repository and login is fictional.`,
  '-- Regenerate rather than edit. Real data arrives through the game workflow (`pnpm game:project`).',
  '',
  'insert into public.sectors (name, repos) values',
  Object.entries(DEMO_PROJECTS.sectors).map(([name, { repos }]) => `  (${lit(name)}, ${arr(repos)})`).join(',\n'),
  'on conflict (name) do update set repos = excluded.repos;',
  '',
  '-- The migrations already hold the fleets; the demo gives them home sectors.',
  'insert into public.teams (name, label, color, motto, mascot, sort, retired_at, home) values',
  Object.entries(DEMO_PROJECTS.teams).map(([name, t]) => `  (${[lit(name), lit(t.label), lit(t.color), lit(t.motto), lit(t.mascot), t.sort, t.retired ? 'now()' : 'null', lit(t.home)].join(', ')})`).join(',\n'),
  'on conflict (name) do update set home = excluded.home;',
  '',
  'insert into public.ledger_events (id, at, type, planet, region, contributor, team, data) values',
  events.map((e) => `  (${[lit(e.id), lit(e.at), lit(e.type), e.planet, lit(e.region), lit(e.contributor), lit(e.team), json(e.data)].join(', ')})`).join(',\n') + ';',
  '',
];
writeFileSync(out, lines.join('\n'));
console.log(`supabase/seed.sql: ${events.length} events across ${new Set(events.map((e) => e.planet)).size} planets`);
