// pnpm galaxy:seed — regenerate supabase/seed.sql from the demo world, dated now.
// `supabase db reset` loads it, so a local stack opens on the same galaxy the demo mode shows.
// The demo galaxy is the `vertuoza` workspace's, which the migrations create with its fleets.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { demoEvents, DEMO_PROJECTS } from '@omni/galaxy';
import { arr, json, lit, workspaceId } from './sql.mjs';

const WORKSPACE = 'vertuoza';
const out = fileURLToPath(new URL('../../../supabase/seed.sql', import.meta.url));
const now = new Date();
const events = demoEvents(now);
const ws = workspaceId(WORKSPACE);

const lines = [
  `-- Generated by \`pnpm galaxy:seed\` on ${now.toISOString()}. Demo data: every PRD, repository and login is fictional.`,
  '-- Regenerate rather than edit. Real data arrives through the game workflow (`pnpm game:project`).',
  `-- Everything below belongs to the \`${WORKSPACE}\` workspace, which the migrations create.`,
  '',
  'insert into public.sectors (workspace_id, name, repos)',
  `select ${ws}, v.name, v.repos from (values`,
  Object.entries(DEMO_PROJECTS.sectors).map(([name, { repos }]) => `  (${lit(name)}, ${arr(repos)})`).join(',\n'),
  ') as v (name, repos)',
  'on conflict (workspace_id, name) do update set repos = excluded.repos;',
  '',
  '-- The migrations already hold the fleets; the demo gives them home sectors.',
  'insert into public.teams (workspace_id, name, label, color, motto, mascot, sort, retired_at, home)',
  `select ${ws}, v.name, v.label, v.color, v.motto, v.mascot, v.sort, v.retired_at::timestamptz, v.home from (values`,
  Object.entries(DEMO_PROJECTS.teams).map(([name, t]) => `  (${[lit(name), lit(t.label), lit(t.color), lit(t.motto), lit(t.mascot), t.sort, t.retired ? 'now()' : 'null', lit(t.home)].join(', ')})`).join(',\n'),
  ') as v (name, label, color, motto, mascot, sort, retired_at, home)',
  'on conflict (workspace_id, name) do update set home = excluded.home;',
  '',
  'insert into public.ledger_events (workspace_id, id, at, type, planet, region, contributor, team, data)',
  `select ${ws}, v.id, v.at::timestamptz, v.type, v.planet, v.region, v.contributor, v.team, v.data from (values`,
  events.map((e) => `  (${[lit(e.id), lit(e.at), lit(e.type), e.planet, lit(e.region), lit(e.contributor), lit(e.team), json(e.data)].join(', ')})`).join(',\n'),
  ') as v (id, at, type, planet, region, contributor, team, data);',
  '',
];
writeFileSync(out, lines.join('\n'));
console.log(`supabase/seed.sql: ${events.length} events across ${new Set(events.map((e) => e.planet)).size} planets, in the ${WORKSPACE} workspace`);
